# config for drone < v0.4
# see https://github.com/drone/drone/blob/v0.3.0/.drone.yml for example

image: node:10
env:
  - NODE_ENV=development
  - NPM_CONFIG_LOGLEVEL=warn
script:
  - env | sort
  - npm install
  - npm run test

# config for drone > v0.4
build:
  test:
    image: node:10
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=warn
    commands:
      - env | sort
      - npm install
      - npm run test
    when:
      event:
        - pull_request
        - push
